### ISSUE TITLE
Read formatting prefs from pom.xml

### ISSUE THREAD

**Issue by tanzoniteblack** [ensime/ensime-maven#18]
Currently we only read scalariform settings from a formatters.properties file, we should also read it from the scalarifrom maven plugin's settings in the pom.xml

Example: https://github.com/tanzoniteblack/ensime-maven/blob/master/pom.xml#L124

**Comment by amanjpro** [comment]
@tanzoniteblack I will be taking care of this. This weekend I will be a bit busy but the next one I will be able to work on it

**Comment by fommil** [comment]
this isn't needed anymore, the ensime 2.0 server no longer does formatting... we are pushing that off to the build tool. But what you might want instead is something similar to sbt-scalariform that formats your code automatically. You can always call the scalariform binary directly from emacs/vim/etc with the file you're editing as a backup.

**Comment by fommil** [comment]
@amanjpro we have ensime stickers that we can send you if you want some! @tanzoniteblack you too, if you don't have any already.

**Comment by amanjpro** [comment]
@fommil thank you for the offer. I will send you my address.

BTW, if this "issue" is no longer valid, shouldn't we just change its label?

**Comment by fommil** [comment]
just create a new one
