### ISSUE TITLE
publish to central

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-maven#2]
as per https://github.com/ensime/ensime-server/issues/1093

**Comment by tanzoniteblack** [comment]
@parsnips where are we with this one? It'd be useful to write some docs about how to use this plugin, but those docs would be significantly improved without having the first step be "clone this repo and run `mvn install`"

**Comment by fommil** [comment]
I set up CI to provide the keys to publish as `org.ensime` to sonatype snapshots, is that working ok?

**Comment by fommil** [comment]
(we could get you added to make releases if you'd like, just raise a ticket on sonatype quoting the org and artefact name and reference this thread, I can do releases to central for you in the meantime).

**Comment by parsnips** [comment]
I haven't tried to publish a snapshot.  I'm assuming we need to provide a `repositories` tag in the maven file as well.

The drone build keeps failing for various non-java/scala related reasons as well.  I'll open a ticket on sonatype later on.  @fommil I'd reccomend just adding @tanzoniteblack to the ensime-maven team as well.  I don't get to work on scala stuff unless its in my ever dwindling free time now.

**Comment by fommil** [comment]
I thought you had access to add him actually, but I'll do it.

**Comment by tanzoniteblack** [comment]
@fommil I requested access for this project https://issues.sonatype.org/browse/OSSRH-19870 so that I'll be able to make releases

**Comment by fommil** [comment]
cool!

**Comment by parsnips** [comment]
At this point artifacts are getting published to sonatype and just need to be released.

**Comment by tanzoniteblack** [comment]
Snapshot artifacts are getting published to sonatype now automatically with merges to master branch. I'm going to go ahead and make a signed release for 0.0.3 and up the pom version to point at 0.0.4-SNAPSHOT so we have a stable version. I think the code base is completely usable as it is at the moment, so it's a good time to do it.

**Comment by tanzoniteblack** [comment]
0.0.3 has been pushed to the central repo and should be available shortly. Once I actually see it on their servers, I'll close this issue.

**Comment by fommil** [comment]
Thanks for picking this up! We know it's important work and apologies I didn't send any PRs your way, just fighting other battles.

**Comment by tanzoniteblack** [comment]
Ok...I didn't get any errors when running `mvn deploy` with the version number set to `0.0.3`, and it uploaded to what looks like the right sonatype repository (i.e. https://oss.sonatype.org/service/local/staging/deploy/maven2/), but it still hasn't appeared at https://repo1.maven.org/maven2/org/ensime/ .

**Comment by fommil** [comment]
is this your first time making a release on sonatype? Because there is one extra step you need to make the first time, raising a ticket or something. And then you've used the web ui to close and release?

**Comment by tanzoniteblack** [comment]
This is my first time making a release on sonatype. Didn't see anything in the docs about needing to use the web ui, but might not've read them close enough.

**Comment by parsnips** [comment]
Yeah in the web ui on releases there's a  [process](http://central.sonatype.org/pages/releasing-the-deployment.html) that involves "closing" repos:

**Comment by parsnips** [comment]
I dont know how up to date that link is, but last time I released jdub, that's what I had to follow.

**Comment by fommil** [comment]
you've both seen this, right? http://play.textadventures.co.uk/Play.aspx

**Comment by tanzoniteblack** [comment]
@fommil that's...depressingly realistic so far. Feels like it should be easy, I publish to private repos all the time, I should know what I'm doing right? Right!?! Oh well!

I've closed and released a version through the web UI and have opened a ticket about getting my sync processes going on after my first release to sonatype. *Hopefully* that's the thing that did it.

**Comment by tanzoniteblack** [comment]
And it's actually visible on one of their public main servers now!

https://repo1.maven.org/maven2/org/ensime/maven/plugins/ensime-maven/0.0.3/

**Comment by fommil** [comment]
yay!
