### ISSUE TITLE
move docs/readme to ensime.org

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-maven#20]
we are trying to consolidate all docs. Please move your README to http://ensime.github.io/build_tools/maven/ and follow the README convention e.g. https://raw.githubusercontent.com/ensime/ensime-server/master/README.md

the other half of https://github.com/ensime/ensime.github.io/issues/9

**Comment by tanzoniteblack** [comment]
Once https://github.com/ensime/ensime.github.io/pull/23 is merged, I'll change the local readme

**Comment by amanjpro** [comment]
Done
