### ISSUE TITLE
ConfigGenerator.getJavaHome() cannot work on windows

### ISSUE THREAD

**Issue by neXtack** [ensime/ensime-maven#21]
On Windows, the "javac" dose not exists, but "javac.exe" does. 
So `org.ensime.maven.plugins.ensime.ConfigGenerator.getJavaHome()` always throws  FileNotFoundException.
I touch a file named `javac`,It's OK.

**Comment by kpadmasola** [comment]
Created PR https://github.com/ensime/ensime-maven/pull/23 for fixing this.

**Comment by fommil** [comment]
I wonder if perhaps the methodology should align with ensime-sbt?

**Comment by timcharper** [comment]
Do you mean that `ensime-sbt` should do platform detection, and write it to a `.ensime` config file?

**Comment by fommil** [comment]
i mean translate https://github.com/ensime/ensime-sbt/blob/2f532c1b0d6c4d609d57bf65d69b000b9e375af5/src/main/scala/EnsimePlugin.scala#L497-L513 into java

**Comment by tanzoniteblack** [comment]
@fommil does that code work on Windows? The code we have here is the same logic, but looking for the executable `javac` instead of `tools.jar`. And while `tools.jar` would be more universal than `javac` (which is `javac.exe` on windows), the fact you're looking for `/lib/tools.jar` screams an issue on Windows, which uses `\` instead of `/` for path separation.

**Comment by fommil** [comment]
yes, it works on windows.

**Comment by kpadmasola** [comment]
I'll send out an updated PR soon based on `tools.jar` check as suggested.

**Comment by kpadmasola** [comment]
@fommil, I updated the PR based on the suggestions, please review. Thanks.

**Comment by fommil** [comment]
LGTM! I had one small suggestion that appears to have gone missing.

**Comment by kpadmasola** [comment]
@fommil , I updated the PR to use forward slashes on Widows when writing out paths as suggested. Please review.

**Comment by kpadmasola** [comment]
@fommil, missed closing this via PR, can you close this issue? Thanks.
