### ISSUE TITLE
RFE Javadocs

### ISSUE THREAD

**Issue by rstebbing** [ensime/ensime-maven#26]
I'm new to Scala and the Java ecosystem (so please forgive any misuse of terminology), but I _think_ that currently, the required Javadoc information is not set in the generated `.ensime` file which prevents looking up documentation (e.g. using `ensime-emacs`). An example project that highlights this is [`ensime-show-doc-for-symbol-at-point`](https://github.com/rstebbing/ensime-show-doc-for-symbol-at-point), where the [pom.xml](https://github.com/rstebbing/ensime-show-doc-for-symbol-at-point/blob/master/project/pom.xml) and generated [.ensime](https://github.com/rstebbing/ensime-show-doc-for-symbol-at-point/blob/master/project/.ensime) files are provided.

**Comment by tanzoniteblack** [comment]
I believe that this is solved by https://github.com/ensime/ensime-maven/pull/30/ and will be available in 0.0.5 (which I will release shortly)
