### ISSUE TITLE
can you please check :target ?

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-maven#27]
I'm about to deprecate `:target` and `:test-target` in favour of `:targets` and `:test-targets` (actually the server makes no differentiation so you can just use `:targets`). Can you check that you are compatible with this?

**Comment by fommil** [comment]
addressed in #28 @tanzoniteblack can you push out a new release please?

**Comment by tanzoniteblack** [comment]
@fommil 0.0.4 has been released
