### ISSUE TITLE
update to .ensime format for 2.0

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-maven#31]
@yilinwei best place to look https://github.com/ensime/ensime-sbt/blob/2.0/src/main/scala/EnsimePlugin.scala#L685-L724

and just above it are the case class definitions.

**Comment by yilinwei** [comment]
@fommil Awesome, will take a look at it.

**Comment by amanjpro** [comment]
@yyadavalli @fommil is anybody working on supporting format 2.0 for maven? If not I would be glad to do ti.

**Comment by yyadavalli** [comment]
Not that I know of. Please go ahead.

**Comment by amanjpro** [comment]
Thank you. I will go for it. I am new to the code base, can anybody point me to the specs of ensime1 and/or ensime2 format.

**Comment by amanjpro** [comment]
Thank you a lot. Will take a look at it

**Comment by amanjpro** [comment]
Pull request 32 closes this
