### ISSUE TITLE
Fix the description of this repo

### ISSUE THREAD

**Issue by amanjpro** [ensime/ensime-maven#33]
The description of this repo wrongfully states that it generates .ensime config files for `SBT`. I couldn't fix it myself.

Here is a screenshot of it:

<img width="742" alt="screen shot 2017-02-11 at 12 10 52 pm" src="https://cloud.githubusercontent.com/assets/3101099/22855788/a15f861a-f053-11e6-8b50-bfe2ec428137.png">

**Comment by fommil** [comment]
done, also updated the website
