### ISSUE TITLE
Could not find artifact org.ensime:server_2.10:jar:2.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by bleshik** [ensime/ensime-maven#40]
When I run "mvn ensime:generate", I get the following error:
[ERROR] Could not find artifact org.ensime:server_2.10:jar:2.0.0-SNAPSHOT in central (https://repo.maven.apache.org/maven2) -> [Help 1]

**Comment by amanjpro** [comment]
Issue #38 and #35 address this issue.

I am not sure why `org.ensime:server_2.10:jar:2.0.0-SNAPSHOT` is not found maybe `org.ensime` has dropped the SNAPSHOT? or do you have snapshots repository added to your build?

```xml
<distributionManagement>
    <snapshotRepository>
      <id>sonatype-nexus-snapshots</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </snapshotRepository>
</distributionManagement>
```

**Comment by bleshik** [comment]
Here is pom.xml:
`
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>groupId</groupId>
    <artifactId>artifact</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>
    <name>artifact</name>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <build>
        <plugins>
            <plugin>
                <groupId>org.ensime.maven.plugins</groupId>
                <artifactId>ensime-maven</artifactId>
                <version>0.0.6</version>
            </plugin>
        </plugins>
    </build>
</project>
`
Here is ~/.m2/settings.xml:
`
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
    https://maven.apache.org/xsd/settings-1.0.0.xsd">
    <localRepository/>
    <interactiveMode/>
    <usePluginRegistry/>
    <offline/>
    <pluginGroups>
        <pluginGroup>org.ensime.maven.plugins</pluginGroup>
    </pluginGroups>
    <servers/>
    <mirrors/>
    <proxies/>
    <profiles/>
    <activeProfiles/>
</settings>
`

**Comment by amanjpro** [comment]
Can you add this to your `pom.xml` file and report if it still has issues:

```xml
<distributionManagement>
    <snapshotRepository>
      <id>sonatype-nexus-snapshots</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </snapshotRepository>
    <repository>
      <id>sonatype-nexus</id>
      <url>https://oss.sonatype.org/service/local/staging/deploy/maven2/</url>
    </repository>
  </distributionManagement>
```

**Comment by bleshik** [comment]
I'm getting same error.

**Comment by amanjpro** [comment]
That is a bit strange, are you sure you have added the snapshot repository correctly, can I see the `pom.xml` after adding the repo? According to this the ensime_2.10 version 2.0.0-SNAPSHOT is in the repo: 

https://oss.sonatype.org/content/repositories/snapshots/org/ensime/server_2.10/2.0.0-SNAPSHOT/

Can you confirm that when you tried it you were connected to internet? Thank you again for using ensime and the maven plugin.

**Comment by amanjpro** [comment]
Just to let you know, a new version is within sights, tomorrow or the day after, that will polish some rough edges of the plugin.

**Comment by amanjpro** [comment]
Can you try version 1.0.0 of the plugin? basically bump the version of ensime-maven from 0.0.6 to 1.0.0

**Comment by bleshik** [comment]
Oh, wow, that's fast. It works, thanks! But I think you should bump the version here http://ensime.org/build_tools/maven/ as well.

**Comment by amanjpro** [comment]
Thanks for confirming that it works. The official site will be updated as soon as its PR gets approved.
