### ISSUE TITLE
drop the scala dependency

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-maven#5]
it sounds like a recipe for disaster to have a scala dependency in a maven plugin

**Comment by amanjpro** [comment]
I am thinking of rewriting the plugin in Java

**Comment by amanjpro** [comment]
My use case is, at my company we are using Scala 2.10 (I know, archaic) and cross compiling scala projects managed by maven is not an easy task. So moving to pure Java will fix this (and the project does not really rely on the power of Scala, sure Scala makes it more concise and easier to read/write but that is another story).

I am also not sure about the ENJIME project, does it use the same config files generated by {sbt,maven,gradle}-plugins?

**Comment by fommil** [comment]
ENJIME is just a synonym for ensime... it's the same server. we cross build the server for 2.10/2.11/2.12. ensime 1.0 was built with java 6, but now requires java 8.

**Comment by amanjpro** [comment]
PR #43 closes this issue

**Comment by fommil** [comment]
Nice!
