### ISSUE TITLE
Your build tool has downloaded the stable version of ENSIME but you are using the Developer Emacs install

### ISSUE THREAD

**Issue by ambjlon** [ensime/ensime-maven#51]
system environment:
emacs24.5
maven-ensime-1.1.1
scala 2.12.1
And, I installed ensime throught melpa.

when I typed M-x ensime, I got an error:
Your build tool has downloaded the stable version of ENSIME but you are using the Developer Emacs install

**Comment by amanjpro** [comment]
Looking at your `pom.xml` file, everything looks OK. Could you try to put the ensime plugin in the root `pom` and run ensime:config in the root level?

**Comment by amanjpro** [comment]
Looking at this line, the build should only work with 2.0.0-SNAPSHOT

https://github.com/ensime/ensime-maven/blob/master/src/main/java/org/ensime/maven/plugins/ensime/EnsimeConfigGenerator.java#L86

Can you send me the generated `.ensime` file?

**Comment by ambjlon** [comment]
Have send .ensime to your email.

**Comment by ambjlon** [comment]
mave-ensime plugin only have 1.1.0 and 1.1.1, no 2.0.0.

**Comment by amanjpro** [comment]
Well, true but the version numbers in this plugin does not correspondence to the one in ENSIME server. Starting from version 0.0.6 maven plugin uses ENSIME server 2.0.0-SNAPSHOT

**Comment by amanjpro** [comment]
There is something odd, your .ensime file does not include any ensime-server jars. Will investigate this. Could you mean while put the dependency in your root pom and try to run `ensime:generate` command in the root level?

**Comment by amanjpro** [comment]
Nevermind, I think the maven plugin is for some reason broken will try to find the cause and fix it

**Comment by ambjlon** [comment]
What is root pom? 
I only have one pom.xml in this project.....

**Comment by amanjpro** [comment]
But your pom specifies the parent pom, I thought this means it is part of a multi-module project

**Comment by peterstuart** [comment]
I am having the same issue. Let me know if I can be any help debugging.

**Comment by ambjlon** [comment]
It still cannot  work in the root pom directory. @amanjpro

**Comment by amanjpro** [comment]
This used not to be like this, I will try with the project that I use and see if it is still the case. I believe it happened after the release of ENSIME server 2.0.0-M1

**Comment by amanjpro** [comment]
I cannot reproduce the issue, will try with other projects that I have

**Comment by ambjlon** [comment]
what is your emacs version?

**Comment by ambjlon** [comment]
@amanjpro  I have sent all my project to your email,  including codes and dependency.  You can  reproduce the issue.

**Comment by tristancabel** [comment]
putting ` private final static String ENSIME_SERVER_VERSION = "2.0.0-M3";`  at [EnsimeConfigGenerator](https://github.com/ensime/ensime-maven/blob/master/src/main/java/org/ensime/maven/plugins/ensime/EnsimeConfigGenerator.java#L86) I no longer have this error. 
I am however stuck a bit further with a "server connection closed unexpectedly:  connection broken by remote peer"

**Comment by amanjpro** [comment]
Can you test the latest version of ensime-maven (1.2.0) and see if it fixes the bug?

**Comment by tristancabel** [comment]
It's working for me. 
Thanks

**Comment by amanjpro** [comment]
Cool, thanks 👍
