### ISSUE TITLE
.ensime is too old

### ISSUE THREAD

**Issue by songpeng** [ensime/ensime-maven#53]
Hi, 
I recently tried many times to use `ensime` in `Java` under builder `Maven`. (`sbt` is only used for scala in my situation, and many people use maven to maintain java project)
OS: Mac OS 10.12.5
Emacs version: 25.2, mac port

1. I can generate .ensime with `mvn ensime:generate`
2. But when I run `M-x ensime`, it said my .ensime is too old.  I use the default set up in ensime.org for maven, i.e., add .m2/settings.xml for ensime-maven.  I see the version is 1.1.1, which is the newest one in maven. So I am indeed confused.
3. sbt work fine with ensime in my computer.

4. Minor:
The ensime.org document for maven says:
*This plugin does not currently document how to use the Developer Version of ENSIME Please get involved at https://github.com/ensime/ensime-maven*
But when I enter that site, there is no document. The readme.md relink to the previous one.
Also, the version for ensime-maven is 1.1.0, not the newest, and not consistent with the version for ensime:scalariform in the same page.

Thanks.
Songpeng

**Comment by amanjpro** [comment]
Thanks for filing this issue, I am a little bit busy, but will try to find some time to fix this. I am currently not using ENSIME + maven, as we have finally migrated to SBT :)

**Comment by songpeng** [comment]
Hi, amanjpro,
Thanks for your reply. I am now using meghanada for java in Emacs, which is small and easy to use. Since you have migrerated to SBT, I will learn it and use it under scala in my situation.  Ensime seems to be a cool tool~
Thanks.
Songpeng

**Comment by amanjpro** [comment]
I would rather reopen this issue, so people won't be mislead thinking that it is fixed

**Comment by amanjpro** [comment]
Can you test the latest version of ensime-maven (1.2.0) and see if it fixes the bug?

**Comment by amanjpro** [comment]
The bug should have been fixed now

**Comment by songpeng** [comment]
Hi, amanjpro,
Thanks a lot for your updates. I try ensime 1.2.0 for java,  and it's now can start ensime without warning.
But I found that
1. if add ensime settings in `~/.m2/setting.xml` as the website mentioned, it doesn't work. 
   I have to add ensime info in the pom file, in which I have to break the pom file that team maintains.
2. In my project, I have multiple sub projects, I only add ensime settings in the parent pom. And it only scan my parent structure, but cannot find right reference when I am open a file in sub pom-owned projects.

Anyway, thanks a lot for your information. I now use meghanada, and it works OK though a little slow. And it doesn't need me to chanage my pom. 
I now use ensime for scala, and it works well under sbt builder.
That's my recent tries. 
               Songpeng

**Comment by songpeng** [comment]
Later update.
It works now!
