### ISSUE TITLE
Implement serverIndex goal for maven

### ISSUE THREAD

**Issue by aramesh117** [ensime/ensime-maven#59]
From the conversation with @yyadavalli in the ensime-vim gitter room, we should have the serverIndex goal in maven to support projects that don't have sbt configurations.

**Comment by yyadavalli** [comment]
Also, the sbt plugin now has `ensimeSnapshot` and `ensimeRestore` tasks, which are simple copy paste jobs to manage the caches.

**Comment by aramesh117** [comment]
@yyadavalli Can we open separate issues for those goals? I'd like to create a PR for the serverIndex goal in since there's an immediate need, and we can open up the other two for any others that are interested.

**Comment by yyadavalli** [comment]
@aramesh117  Go ahead open the PR. I will create a new issue as needed.

**Comment by aramesh117** [comment]
https://github.com/ensime/ensime-maven/pull/60. Any reviews would be much appreciated. I've tested it using a local project and it works well.

**Comment by amanjpro** [comment]
PR #60 closes this
