### ISSUE TITLE
snapshots

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-maven#6]
@parsnips if you create a `.drone.yml` file to do the build (take inspiration from ensime-server and install whatever you need, I'll add it to the base docker image eventually) I'll add a `.drone.sec` file which will contain the encrypted environment variables `SONATYPE_USERNAME` and `SONATYPE_PASSWORD` for publication to sonatype. That should let every merge to master publish a snapshot, and I (or any of the other ensime Core) can do a release to central anytime you need. If you want to have publication rights yourself, open a ticket on sonatype requesting access to `org/ensime/ensime-maven` and quote this ticket for permission.

**Comment by fommil** [comment]
@parsnips FYI https://github.com/ensime/ensime-maven/commit/5123e4398d50f1e629ec84d9468de20a4021f548

**Comment by fommil** [comment]
(btw, instead of pushing your commits directly to `ensime/ensime-maven`, just fork the repo and issue PRs that you can merge. That way you'll benefit from the drone CI even if you're merging your own changes.)

**Comment by fommil** [comment]
also, if I may suggest a good project for an integration test: https://commons.apache.org/proper/commons-vfs/ (it's likely that we're going to need to fix some bugs in this upstream dependency of ENSIME)

**Comment by parsnips** [comment]
Thanks @fommil working on this today!

**Comment by fommil** [comment]
:smile:

**Comment by fommil** [comment]
ENSIME Java is coming along nicely, I think we should get initial (a bit hacky) support added within a week and dev will only accelerate from there.

**Comment by amanjpro** [comment]
Is this issue still relevant? I am not seeing merges lead to publishing to sonatype snapshots

**Comment by fommil** [comment]
I can set up the permissions if you want to enable this? There are not many ensime-maven users, so it might just be more efficient to use locally published files until you are happy to cut a main release. Nobody even uses the sbt-ensime snapshots.

**Comment by amanjpro** [comment]
Ah, no need to then. I will mark this issue as won't fix then.
