### ISSUE TITLE
Generate .ensime file without touch settings.xml or pom.xml

### ISSUE THREAD

**Issue by albfan** [ensime/ensime-maven#63]
Is it possible to generate that file without mess in project or system config files

I want to integrate ensime into GNOME Builder and find odd to make users to touch his files to get scala/java lsp features

Maybe there's another project that does this, I just didn't find it

**Comment by amanjpro** [comment]
Thanks for using/integrating ENSIME, I think what you need is 

```
$ mvn  -help
  ...
  -s,--settings <arg>                    Alternate path for the user
                                                     settings file
  ...
```

GNOME builder can basically use this option to provide alternative path to the systems.xml with all the required settings set.

**Comment by albfan** [comment]
Ahh, correct. Will it work for build plugins too? I can check later, afk now

**Comment by amanjpro** [comment]
I have never had to set it, but it should work I believe

**Comment by albfan** [comment]
I think so.
