### ISSUE TITLE
Common SExpr Writer

### ISSUE THREAD

**Issue by parsnips** [ensime/ensime-maven#7]
Should pull out SExpr writer and emitter classes and port them to java to share amongst the groovy, sbt and maven versions.

**Comment by parsnips** [comment]
Should also add common data structures and classes for actually writing a valid .ensime file as well.

**Comment by fommil** [comment]
The plan was to use the ensime-server one from ensime-sbt (eventually). But porting that is highly non-trivial, as it relies on shapeless magic. I'd recommend just limiting this effort to the maven/gradle plugins, but going full Java is definitely a good idea.

**Comment by fommil** [comment]
btw, if you look at the ensime-sbt s-expr writer, you'll see that it's just a massive hack specifically for the `.ensime` file format.

**Comment by fommil** [comment]
I've realised how nice it is to have a single file plugin for sbt (makes it easier to use in corporate environments) so I think the benefits of that outweigh the cost of code logic duplication, so I'll close this one if you don't mind.

**Comment by fommil** [comment]
btw, the canonical code / data structure is always this one https://github.com/ensime/ensime-server/blob/master/api/src/main/scala/org/ensime/api/config.scala

but I suppose there are a few things in `ensime-sbt` that emacs uses that the server doesn't care about, like `:scala-compiler-jars` https://github.com/ensime/ensime-sbt/blob/master/src/main/scala/EnsimePlugin.scala#L553
